.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOLBUILD\.CONF" "5" "December 2016" "" ""
.
.SH "NAME"
\fBsolbuild\.conf\fR \- solbuild configuration
.
.SH "NAME"
.
.nf

solbuild\.conf \- configuration for solbuild
.
.fi
.
.SH "SYNOPSIS"
.
.nf

/usr/share/solbuild/*\.conf

/etc/solbuild/*\.conf
.
.fi
.
.SH "DESCRIPTION"
.
.nf

`solbuild` uses configuration files from the above mentioned directories
to configure various aspects of the `solbuild` defaults\.
.
.fi
.
.SH "CONFIGURATION FORMAT"
.
.SH "EXAMPLE"
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright © 2016 Ikey Doherty, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBsolbuild(1)\fR
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

